---
# tasks file for vicenteg.mapr_mesos_dns

- name: install mapr-mesos-dns
  become: yes
  become_user: root
  yum: name=mapr-mesos-dns state=present
  environment: '{{proxy_env}}'

- name: install mapr-mesos-dns configuration file
  become: yes
  become_user: root
  template: src=config-dns.json.j2 dest=/opt/mapr/mesos-services/mesos-services-0.1/conf/config-dns.json owner=root group=root mode=0644
  #notify: restart mesos-dns
